### ISSUE TITLE
sys.stdout don't always have isatty()

### ISSUE THREAD

**Issue by eventh** [dag/attest#125]
Inside reporters.py, auto_reporter() you test if sys.stdout.isatty() but there are cases where this will raise AttributeError.
For example PyScripter replaces sys.stdout with a graphical replacement, and running tests there will result in an error message: "DebugOutput has no attribute "isatty" ".

You should probably add "if not hasattr(sys.stdout, "isatty")" to that function.

**Comment by SimonSapin** [comment]
Closed by #126.
