### ISSUE TITLE
Add `test_case` method to Tests

### ISSUE THREAD

**Issue by bradleyayers** [dag/attest#132]
I'm using Attest with Django. Django supports running individual tests via `manage.py test app.testcase.method`. Unfortunately `TestSuite` is not supported (not that it would help much anyway since you can't access individual tests within a test suite). I propose adding a `test_case` method to match `test_suite`. A working implementation is (not tested across many situations):

```
def test_case(self):
    from unittest import TestCase
    methods = {}
    for func in self:
        methods["test_{}".format(func.__name__)] = staticmethod(func)
    return type("Tests", (TestCase, ), methods)
```

**Comment by SimonSapin** [comment]
Hi,

As we discussed in #131, Attest is kind of abandoned at the moment. Dag said he would give Github and PyPI access if anyone wants to take over the maintenance. In the meantime, I’ve been using py.test. It is similar to attest but better supported.

**Comment by bradleyayers** [comment]
I gave py.test a go and it's just not as elegant as attest so im going to have a go at continuing development on this.

**Comment by SimonSapin** [comment]
Do you want to take over? I can give you access for the project on PyPI (what’s your user name?) but not on Github. Contact @dag for that. But I guess you could just change the github link in the docs.

**Comment by bradleyayers** [comment]
Sure, my username on PyPI is `bradley.ayers`.

**Comment by SimonSapin** [comment]
Ok, you have admin access to http://pypi.python.org/pypi/Attest

**Comment by bradleyayers** [comment]
Thank-you!
