### ISSUE TITLE
Rename Tests → Collection?

### ISSUE THREAD

**Issue by dag** [dag/attest#16]

**Comment by DasIch** [comment]
Just Collection is a bit generic, the name Tests already makes it obvious that it is a collection of some kind and at least iterable.

**Comment by dag** [comment]
Well I tend to avoid the duplication of naming everything in a package with the category of the package. So Collection is preferable over e.g. TestCollection because by being in the attest package it is clear that it's related to testing (unless _otherwise_ named).

But I suppose Tests is a fine name.

**Comment by dag** [comment]
Closing because I can't make up my mind so I'll instead listen to the feedback.
