### ISSUE TITLE
Rewrite asserts to Asserts with decorator using ast?

### ISSUE THREAD

**Issue by dag** [dag/attest#22]

**Comment by DasIch** [comment]
I'm not sure I like the idea. Manipulating the ast is quite magical and it's probably quite difficult to implement so I wouldn't consider it worth the effort. However I'm not really opposed to it either, writing tests like py.test allows is nice and this approach would have the advantage of being side-effect free(py.test executes assert lines twice to get at the information displayed for failed tests).

**Comment by dag** [comment]
I'm thinking,
1. Not for 0.1
2. Opt-in, at least first until it has been tested enough
3. May never happen, just throwing around ideas :)

I don't like magic either, but a simple rewrite might not be that magical, or it is - I don't know. Haven't ever used the ast module.

Of course you can roll your own DSL easily:

```
from attest import Assert as the
assert 'hello world' in the(response).data
```

or whatever. Assert operations return True if they don't fail.

Mostly, I don't like things like `Assert.is_` (compared to plain `is`) etc.
