### ISSUE TITLE
Rename "formatters"?

### ISSUE THREAD

**Issue by dag** [dag/attest#23]
A GUI wouldn't quite be a "formatter", but neither are the formatters "test runners". "Handlers"?

**Comment by DasIch** [comment]
Handlers doesn't really describe what's happening here, formatter is not a bad choice but as an alternative I think another good choice might be "reporters", which says more about what they actually do.

**Comment by dag** [comment]
"Responder" in that they respond to events from a test run?

I'm considering moving some version of TestFormatter to the core under some name like "CollectingFormatter" or "LoggingFormatter", does "reporter" make sense in that context?

**Comment by dag** [comment]
I'm starting to like "reporter" other than that it makes me think of journalists. I think "handler" is the most correct term _because_ it's so generic - a "formatter" can basically do anything with the data it receives. In a way similar to Logbook handlers, many of which could arguably be called "formatters" or "reporters" but perhaps not all.

**Comment by DasIch** [comment]
Although formatters handle any events their goal is to present the raw data in an easily accessible way, where accessible is defined by the way we want to use the result later on.

Looking for a name of something that is collecting, filtering and presenting data "Reporter" seems like a good choice.

I don't think they are doing anymore and given that the fact that the name "handler" doesn't say anything but that it handles something unless given more context I think that it's probably too generic.

**Comment by dag** [comment]
Rename formatters to reporters, closed by 85fea536e316cefe4e73fa889d9555ad34324fe8
