### ISSUE TITLE
output and debugging

### ISSUE THREAD

**Issue by gabrielelanaro** [dag/attest#71]
I'm using Attest 0.4 and I'm having trouble with the stdout handling using the PlainReporter. I usually debug my program with print statements/logging but seems that it captures the output in some way.

There's a recommendend practice to handle this situation?

**Comment by dag** [comment]
Ah right, I never added printing of the captured output to the plain reporter. FancyReporter shows them; a sensible format for PlainReporter wasn't obvious to me at the time. How about something like,

```
-> this line came from stdout
E: and this one from stderr
```

**Comment by gabrielelanaro** [comment]
I think that this format is fine (with the same behaviour of FancyReporter). Thank you for the fast response!

**Comment by dag** [comment]
Show console output from tests with PlainReporter, closed by 213fc016066efad0f29be18165c69660fd87fa5b
