### ISSUE TITLE
A failing "assert exp1, exp2" should output both exp1 and exp2

### ISSUE THREAD

**Issue by stony8** [dag/attest#72]
If exp1 was false,
<code>assert exp1, exp2</code>
should output exp2 (current behavior) <b>and</b> exp1 evaluated.
E.g.
<code>assert actual == expected, "check '%s': unexpected value"</code>
could result in
<code>AssertionError: not ('Rome' == 'Venice'), check 'city': unexpected value</code>
or
<code>AssertionError: check 'city': unexpected value: not ('Rome' == 'Venice')</code>
While the former preserves the order of exp1 and exp2, the latter is more
readable (at least in this example).

Such a feature is useful in tests which have several assert statements (possibly
in loops) where you want to see a distinctive message (exp2) <b>and</b> the evaluated
operands of exp1.

**Comment by dag** [comment]
Good idea. Will require some refactoring as currently (on HEAD) the message for AssertionError is assumed to be valid Python and highlighted as such. I've been considering anyway if the assert hook should raise a different exception (probably a subclass of AssertionError) with more detailed metadata.

**Comment by dag** [comment]
Fixed in 31b3ceb38e29e02ab6988a61072c0d9f8c9df963
