### ISSUE TITLE
Hook should raise custom TestFailure exception

### ISSUE THREAD

**Issue by dag** [dag/attest#74]
- Holds custom metadata such as evaluation steps (#73)
- Separates assertion message and evaluated expression (#72)
- Instantly obvious if the hook was used in a failing test

**Comment by stony8** [comment]
<ul><li> Delegates part of the output generation to a "smart diff" á lá py.test if a == comparison and builtin types are involved?</li></ul>

**Comment by dag** [comment]
Suchthings are in deed desirable, and a custom exception type is a step in that direction.

Actually I just now thought of an easy way to do this (I hope) that might not be perfect but maybe still useful: use difflib to generate a unified diff of the pprint.pformat(width=1) of compared objects, color udiff with pygments.

Because binary logic can bind comparisons it'd need to loop all and for clarity probably display the to_source of each comparison node before their corresponding diffs.
