### ISSUE TITLE
Getting real sys.stdout, sys.stderr

### ISSUE THREAD

**Issue by DasIch** [dag/attest#78]
I'm currently writing some tests for which I need a tty. Developing one myself is an effort I'm not willing to undertake so I need to get to the real sys.stdout. I could get it via os.fdopen but simply hard coding the fd wouldn't be platform independent afaik.

**Comment by dag** [comment]
How about http://docs.python.org/library/sys.html#sys.__stdin__ ?

**Comment by DasIch** [comment]
That should do it. :/
