### ISSUE TITLE
List comprehensions and Generator Expression fail with assert hook

### ISSUE THREAD

**Issue by DasIch** [dag/attest#81]
If I use the assert_hook I get NameErrors for LCs and genexps e.g.:

```
assert [foo for foo in bar] == spam
```

Will raise a NameError because 'foo' is not defined. I've tried to write a test case and came up with this http://paste.pocoo.org/show/351508/ not sure if it is correct but it does raise a NameError for 'foo' which certainly shouldn't happen.

**Comment by dag** [comment]
Evaluate comprehensions, closed by 6c369d1e5024b82e89fc798655b6b8e678f29bb0 I hope
