### ISSUE TITLE
Wrong requirements in setup.py

### ISSUE THREAD

**Issue by bradleyayers** [dag/attest#85]
Version 0.4 seemed to be fine with progressbar 2.2, however it seems that in 0.5.1 it now requires >= progressbar 2.3-dev (it's a shame the version syntax is wrong also [it should be a . rather than a - as the separator). I got caught with this because I store all the packages required for my project locally.

**Comment by dag** [comment]
Progressbar dependency &gt;=2.3-dev, closed by 5da233c2cb6a74ab8bc3c5758d3279598ed22c88

**Comment by bradleyayers** [comment]
Thanks dag! I've notified the author of progressbar about the versioning syntax, so hopefully that will be fixed soon too.

**Comment by dag** [comment]
Cool; I was considering if they should be asked to release proper soon, it's been -dev since August.
