### ISSUE TITLE
Context managers for temporary files and directories

### ISSUE THREAD

**Issue by dag** [dag/attest#87]

**Comment by gabrielelanaro** [comment]
This would be very useful

**Comment by dag** [comment]
Looks like the tempfile module supports this already for files:

``` python
with TemporaryFile() as f:
    f.write(stuff)
```

After the context the file is closed and upon closing it is removed. Seems to work on Python 2.5 even. Similar support for temporary directories is new in 3.2 so we might want to backport that.
