### ISSUE TITLE
How to handle warnings

### ISSUE THREAD

**Issue by dag** [dag/attest#94]
- Should we special-case warnings somehow, or is it good enough that they're printed as output for failing tests?
- Would a context manager be useful? There is one in the warnings library already but it seems possibly clunky.

**Comment by bradleyayers** [comment]
I want to be able to test that a warning is caused by a block of code. A context manager makes sense, e.g.

```
with attest.warns(DeprecationWarning):
    foo()
```

A few things to consider:
- How to handle multiple warnings from a single block
- How to handle arbitrary current filters for warnings

**Comment by bradleyayers** [comment]
I've written an implementation for this: https://github.com/bradleyayers/attest/blob/master/attest/contexts.py#L167 feedback welcome.
